export const COLLECTIONS = {
    ACCOUNTS: 'accounts',
    ATTENDANCE: 'attendance',
    BRANDS: 'brands',
    CATEGORIES: 'categories',
    COUNTERS: 'counters',
    CUSTOMERS: 'customers',
    DAILY_STOCK: 'dailyStock',
    DEPARTMENTS: 'departments',
    DESIGNATIONS: 'designations',
    EXPENSE_CATEGORIES: 'expense-categories',
    EXPENSES: 'expenses',
    GIN_TRANSFERS: 'gin-transfers',
    GOODS_RECEIVED: 'goodsReceived',
    HOLIDAYS: 'holidays',
    INCOME_CATEGORIES: 'income-categories',
    INCOMES: 'incomes',
    LEAD_STATUSES: 'leadStatuses',
    LEADS: 'leads',
    LEAVE_TYPES: 'leave-types',
    LEAVES: 'leaves',
    LIFE_STAGES: 'lifeStages',
    LOCATIONS: 'locations',
    PAYMENTS: 'payments',
    PAYROLLS: 'payrolls',    PRODUCT_STOCK: 'product-stock',
    PRODUCT_STOCK_HISTORY: 'product-stock-history',
    // PRODUCT_HISTORY: 'product_history', // These are just logs
    // PRODUCT_STOCK_HISTORY: 'product_stock_history', // These are just logs
    PRODUCTS: 'products', // Note: Using underscore to avoid conflict with Firestore reserved keywords
    PURCHASE_ORDERS: 'purchase-orders',
    PURCHASE_REQUISITIONS: 'purchase-requisitions',
    PURCHASE_RETURNS: 'purchase-returns',
    PURCHASES: 'purchases',
    ROLES: 'roles',
    SALES: 'sales',
    SALES_AGENTS: 'sales-agents',
    SERVICES: 'services',
    SHIFTS: 'shifts',
    SOURCES: 'sources',
    STOCK_ADJUSTMENTS: 'stock-adjustments',
    STOCK_TRANSFERS: 'stock_movements',
    SUPPLIERS: 'suppliers',
    TAX_RATES: 'taxRates',
    TRANSACTIONS: 'transactions',
    UNITS: 'units',
    USERS: 'users',
    WARRANTIES: 'warranties'
};
